### ISSUE TITLE
Menu key does not bring up main menu dialog

### ISSUE THREAD

**Issue by jgabaut** [Vaiterius/Traditional-Roguelike#2]
I hope this does not come off as a nitpick, since it's just my honest report on first-hand usage.

What I did:

- Clone, run
- Notice I can't open a menu in "exploration" state
- Go to `README`
- Find "main menu" hint
- Found: 
```
  To go back to main menu:

  - m
```

Which ATM is not working.

I later realised there's also:
```
To exit:

- Q
```

Which asks to go to main menu as promised. I understand why you would not want an immediate-quit key (user may press it by accident when playing), but in my opinion the exit key should close the game altogether (after a "confirm" prompt, I'd prefer) while the menu key should bring you back to main menu.

I would open a separate issue to describe the fact that the exit key brings you to main menu, but that may be intended behaviour.

**Comment by jgabaut** [comment]
I opened #1 to band-aid fix the usage of `m` key for getting the existing main menu prompt.
I don't know if a `MENU_KEYS` would be appropriate to add, check the code comment.

**Comment by Vaiterius** [comment]
Hi, I agree with your decision to have a key to go back to the main menu and another key to close the game altogether. At the moment, the game is not finished yet so everything is still under development. When I finish, I will gladly welcome any feedback/quality of life improvements/bug fixes from anyone. 

I'll update the README to include more information regarding the state of the game and I'll pull your changes but I'd ask to hold off on any more fixes until the game is ready, thanks!

Also, how did you find my repo? 😅

**Comment by jgabaut** [comment]
Thanks for your patience and kind reply. I'm gonna follow your suggestion and check on development every once in a while.

As for the repo find, I have a simple game repo myself, and I was just scrolling some similar tagged ones, and yours really captured my attention with the description (old-style is good style). 😄

**Comment by Vaiterius** [comment]
Cool! I'll check yours out too, curses is such a pain to work with ngl 😣
