### ISSUE TITLE
Color pairs are overfilled

### ISSUE THREAD

**Issue by jjszaniszlo** [Vaiterius/Traditional-Roguelike#3]
It seems that on my terminal emulator, I'm getting this error when trying to run the game using python 3.11.2 on MacOS.  It seems that the loop overfills the pairs array.  I'm not a python dev so I don't know much about the language or curses, so I'm not sure if the loop should go from 0-255 including 255.  The error says greater than 255, so it's possible that it's looping from 0-256 unintentionally. 

<img width="1078" alt="Screenshot 2024-01-29 at 2 37 34 PM" src="https://github.com/Vaiterius/Traditional-Roguelike/assets/40372435/13a301e8-dd57-4d8a-bfd4-c03a3a8155be">

**Comment by jjszaniszlo** [comment]
<img width="761" alt="Screenshot 2024-01-29 at 3 29 15 PM" src="https://github.com/Vaiterius/Traditional-Roguelike/assets/40372435/52ddfcb3-8100-40ca-8527-19ca3e94f01c">

it seems that curses.COLORS is defined depending on the platform and terminal itself, so I'm not quite sure what could cause it to overflow besides an error with the range :/

**Comment by Vaiterius** [comment]
Thanks for bringing this up. Honestly, with MacOS users I have no idea about their situation, but one other person using Linux worked fine with them as far as I know. I could look more into support for different terminals. Does your #4 make the game run for you?

**Comment by jjszaniszlo** [comment]
yep, #4 made it work.  It might be some weird platform code down the line somewhere.  curses is natively supported on all unix systems, so it definitely should have theoretically worked right out of the box.

**Comment by Vaiterius** [comment]
Ran it with no apparent issues on my end, I approve 👍
